// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

public partial class ProjectDbContext : DbContext
{
    public ProjectDbContext(DbContextOptions<ProjectDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Sys_BasicSetting> Sys_BasicSettings { get; set; }

    public virtual DbSet<Sys_UserInfo> Sys_UserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Sys_BasicSetting>(entity =>
        {
            entity.HasKey(e => new { e.Type, e.Key }).HasName("PK_SYS_SysSettings");

            entity.ToTable(tb => tb.HasComment("系統設定參數表"));

            entity.Property(e => e.Type).HasComment("設定類型（複合主鍵之一）");
            entity.Property(e => e.Key).HasComment("設定鍵值（複合主鍵之一）");
            entity.Property(e => e.CreatedId).HasComment("建立者帳號（對應 Sys_UserInfo.UserId）");
            entity.Property(e => e.CreatedTime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("建立時間");
            entity.Property(e => e.Label).HasComment("設定說明標籤");
            entity.Property(e => e.Value).HasComment("設定值");
        });

        modelBuilder.Entity<Sys_UserInfo>(entity =>
        {
            entity.ToTable("Sys_UserInfo", tb => tb.HasComment("系統使用者資訊表"));

            entity.Property(e => e.Id).HasComment("流水號（主鍵）");
            entity.Property(e => e.CreatedId).HasComment("建立者ID");
            entity.Property(e => e.CreatedTime)
                .HasComment("建立時間")
                .HasDefaultValueSql("(getdate())", "DF__Sys_UserI__Creat__276EDEB3");
            entity.Property(e => e.Email).HasComment("電子郵件");
            entity.Property(e => e.IsEnable)
                .HasComment("啟用狀態（1=啟用, 0=停用）")
                .HasDefaultValue(true, "DF__Sys_UserI__IsEna__267ABA7A");
            entity.Property(e => e.LastLoginIp).HasComment("最後登入IP位址");
            entity.Property(e => e.LastLoginTime).HasComment("最後登入時間");
            entity.Property(e => e.LoginFailCount).HasComment("登入失敗次數");
            entity.Property(e => e.Password).HasComment("密碼（雜湊值）");
            entity.Property(e => e.UpdatedId).HasComment("更新者ID");
            entity.Property(e => e.UpdatedTime).HasComment("更新時間");
            entity.Property(e => e.UserId).HasComment("使用者帳號");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}