// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

[Table("Sso_Client")]
[Index("IsEnable", Name = "IX_Sso_Client_IsEnable")]
[Index("ClientId", Name = "UQ_Sso_Client_ClientId", IsUnique = true)]
public partial class Sso_Client
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string ClientId { get; set; }

    [Required]
    [StringLength(200)]
    public string ClientName { get; set; }

    [Required]
    [StringLength(500)]
    public string ClientSecretHash { get; set; }

    public bool IsEnable { get; set; }

    public DateTime CreatedTime { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    public DateTime UpdatedTime { get; set; }

    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }
}