// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 系統角色群組資料表
/// </summary>
[Table("Sys_RoleGroup")]
[Index("IsEnable", Name = "IX_Sys_RoleGroup_IsEnable")]
[Index("ParentRoleGroupId", "SortOrder", Name = "IX_Sys_RoleGroup_ParentRoleGroupId_SortOrder")]
public partial class Sys_RoleGroup
{
    /// <summary>
    /// 角色群組 ID
    /// </summary>
    [Key]
    public int RoleGroupId { get; set; }

    /// <summary>
    /// 上層角色群組 ID，NULL 代表根節點
    /// </summary>
    public int? ParentRoleGroupId { get; set; }

    /// <summary>
    /// 角色群組名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string RoleGroupName { get; set; }

    /// <summary>
    /// 角色群組描述
    /// </summary>
    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    /// <summary>
    /// 排序值
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public bool IsEnable { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime UpdatedTime { get; set; }

    /// <summary>
    /// 更新人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }

    public virtual ICollection<Sys_RoleGroup> InverseParentRoleGroup { get; set; } = new List<Sys_RoleGroup>();

    public virtual Sys_RoleGroup ParentRoleGroup { get; set; }

    [InverseProperty("RoleGroup")]
    public virtual ICollection<Sys_RoleGroupFunctionPermission> Sys_RoleGroupFunctionPermissions { get; set; } = new List<Sys_RoleGroupFunctionPermission>();

    [InverseProperty("RoleGroup")]
    public virtual ICollection<Sys_UserRoleGroup> Sys_UserRoleGroups { get; set; } = new List<Sys_UserRoleGroup>();
}
