// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 角色群組功能操作權限對應表
/// </summary>
[PrimaryKey("RoleGroupId", "FunctionPermissionId")]
[Table("Sys_RoleGroupFunctionPermission")]
[Index("FunctionPermissionId", Name = "IX_Sys_RoleGroupFunctionPermission_FunctionPermissionId")]
public partial class Sys_RoleGroupFunctionPermission
{
    /// <summary>
    /// 角色群組 ID
    /// </summary>
    [Key]
    public int RoleGroupId { get; set; }

    /// <summary>
    /// 功能操作權限 ID
    /// </summary>
    [Key]
    public int FunctionPermissionId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    [ForeignKey("FunctionPermissionId")]
    [InverseProperty("Sys_RoleGroupFunctionPermissions")]
    public virtual Sys_FunctionPermission FunctionPermission { get; set; }

    [ForeignKey("RoleGroupId")]
    [InverseProperty("Sys_RoleGroupFunctionPermissions")]
    public virtual Sys_RoleGroup RoleGroup { get; set; }
}