// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 使用者角色群組對應表
/// </summary>
[PrimaryKey("UserId", "RoleGroupId")]
[Table("Sys_UserRoleGroup")]
[Index("RoleGroupId", Name = "IX_Sys_UserRoleGroup_RoleGroupId")]
public partial class Sys_UserRoleGroup
{
    /// <summary>
    /// 使用者帳號
    /// </summary>
    [Key]
    [StringLength(50)]
    public string UserId { get; set; }

    /// <summary>
    /// 角色群組 ID
    /// </summary>
    [Key]
    public int RoleGroupId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    public virtual Sys_RoleGroup RoleGroup { get; set; }

    public virtual Sys_UserInfo User { get; set; }
}
