// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 系統功能操作權限資料表
/// </summary>
[Table("Sys_FunctionPermission")]
[Index("FunctionCode", "OperationCode", Name = "IX_Sys_FunctionPermission_FunctionCode_OperationCode")]
[Index("IsEnable", Name = "IX_Sys_FunctionPermission_IsEnable")]
[Index("ParentFunctionPermissionId", "SortOrder", Name = "IX_Sys_FunctionPermission_ParentFunctionPermissionId_SortOrder")]
[Index("PermissionKey", Name = "UQ_Sys_FunctionPermission_PermissionKey", IsUnique = true)]
public partial class Sys_FunctionPermission
{
    /// <summary>
    /// 功能操作權限 ID
    /// </summary>
    [Key]
    public int FunctionPermissionId { get; set; }

    /// <summary>
    /// 上層功能操作權限 ID，NULL 代表根節點
    /// </summary>
    public int? ParentFunctionPermissionId { get; set; }

    /// <summary>
    /// 權限鍵值，功能節點使用 FunctionCode，操作節點使用 FunctionCode:OperationCode
    /// </summary>
    [Required]
    [StringLength(150)]
    public string PermissionKey { get; set; }

    /// <summary>
    /// 功能代碼
    /// </summary>
    [Required]
    [StringLength(100)]
    public string FunctionCode { get; set; }

    /// <summary>
    /// 功能名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string FunctionName { get; set; }

    /// <summary>
    /// 操作代碼：C 新增、R 讀取、U 更新、D 刪除、A 審核、F 檔案上傳/下載；NULL 代表功能節點
    /// </summary>
    [StringLength(10)]
    public string OperationCode { get; set; }

    /// <summary>
    /// 操作名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string OperationName { get; set; }

    /// <summary>
    /// 排序值
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public bool IsEnable { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime UpdatedTime { get; set; }

    /// <summary>
    /// 更新人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }

    public virtual ICollection<Sys_FunctionPermission> InverseParentFunctionPermission { get; set; } = new List<Sys_FunctionPermission>();

    public virtual Sys_FunctionPermission ParentFunctionPermission { get; set; }

    [InverseProperty("FunctionPermission")]
    public virtual ICollection<Sys_RoleGroupFunctionPermission> Sys_RoleGroupFunctionPermissions { get; set; } = new List<Sys_RoleGroupFunctionPermission>();
}
