// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 系統選單樹資料表
/// </summary>
[Table("Sys_MenuTree")]
[Index("IsEnable", Name = "IX_Sys_MenuTree_IsEnable")]
[Index("ParentId", "SortOrder", Name = "IX_Sys_MenuTree_ParentId_SortOrder")]
[Index("MenuCode", Name = "UQ_Sys_MenuTree_MenuCode", IsUnique = true)]
public partial class Sys_MenuTree
{
    /// <summary>
    /// 主鍵
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 父層選單 ID，NULL 表示根選單
    /// </summary>
    public int? ParentId { get; set; }

    /// <summary>
    /// 唯一選單代碼，供前端或權限邏輯識別選單
    /// </summary>
    [Required]
    [StringLength(100)]
    public string MenuCode { get; set; }

    /// <summary>
    /// 顯示選單名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string MenuName { get; set; }

    /// <summary>
    /// 圖示名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Icon { get; set; }

    /// <summary>
    /// 同層排序
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public bool IsEnable { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime UpdatedTime { get; set; }

    /// <summary>
    /// 更新人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }

    public virtual ICollection<Sys_MenuTree> InverseParent { get; set; } = new List<Sys_MenuTree>();

    public virtual Sys_MenuTree Parent { get; set; }
}
