// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 系統使用者資訊表
/// </summary>
[Table("Sys_UserInfo")]
[Index("Email", Name = "IX_Sys_UserInfo_Email")]
[Index("IsEnable", Name = "IX_Sys_UserInfo_IsEnable")]
[Index("UserId", Name = "UQ_Sys_UserInfo_UserId", IsUnique = true)]
public partial class Sys_UserInfo
{
    /// <summary>
    /// 流水號（主鍵）
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 使用者帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    /// <summary>
    /// 密碼（雜湊值）
    /// </summary>
    [Required]
    [StringLength(500)]
    public string Password { get; set; }

    [Required]
    [StringLength(50)]
    public string DeptId { get; set; }

    [Required]
    [StringLength(20)]
    public string MobilePhone { get; set; }

    /// <summary>
    /// 電子郵件
    /// </summary>
    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    /// <summary>
    /// 登入失敗次數
    /// </summary>
    public int LoginFailCount { get; set; }

    /// <summary>
    /// 啟用狀態（1=啟用, 0=停用）
    /// </summary>
    public bool IsEnable { get; set; }

    /// <summary>
    /// 最後登入時間
    /// </summary>
    public DateTime? LastLoginTime { get; set; }

    /// <summary>
    /// 最後登入IP位址
    /// </summary>
    [StringLength(50)]
    public string LastLoginIp { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立者ID
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime UpdatedTime { get; set; }

    /// <summary>
    /// 更新者ID
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }
}