// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 系統設定參數表
/// </summary>
[PrimaryKey("Type", "Key")]
public partial class Sys_BasicSetting
{
    /// <summary>
    /// 設定類型（複合主鍵之一）
    /// </summary>
    [Key]
    [StringLength(50)]
    public string Type { get; set; }

    /// <summary>
    /// 設定鍵值（複合主鍵之一）
    /// </summary>
    [Key]
    [StringLength(100)]
    public string Key { get; set; }

    /// <summary>
    /// 設定值
    /// </summary>
    public string Value { get; set; }

    /// <summary>
    /// 設定說明標籤
    /// </summary>
    [StringLength(200)]
    public string Label { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立者帳號（對應 Sys_UserInfo.UserId）
    /// </summary>
    [StringLength(50)]
    public string CreatedId { get; set; }
}