// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

[Table("Sys_Department")]
[Index("IsEnable", Name = "IX_Sys_Department_IsEnable")]
[Index("ParentDeptId", "SortOrder", Name = "IX_Sys_Department_ParentDeptId_SortOrder")]
public partial class Sys_Department
{
    [Key]
    public int DeptId { get; set; }

    [Required]
    [StringLength(100)]
    public string DeptName { get; set; }

    public int? ParentDeptId { get; set; }

    public int SortOrder { get; set; }

    public bool IsEnable { get; set; }

    public DateTime CreatedTime { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    public DateTime UpdatedTime { get; set; }

    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }

    public virtual ICollection<Sys_Department> InverseParentDept { get; set; } = new List<Sys_Department>();

    public virtual Sys_Department ParentDept { get; set; }
}
