// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.ProjectDbContext;

/// <summary>
/// 背景工作資料庫佇列表
/// </summary>
[Table("Sys_BackgroundJob")]
[Index("WorkType", "Status", "ScheduledTime", "Priority", Name = "IX_Sys_BackgroundJob_Dequeue")]
[Index("WorkKey", Name = "IX_Sys_BackgroundJob_WorkKey")]
public partial class Sys_BackgroundJob
{
    /// <summary>
    /// 工作流水號
    /// </summary>
    [Key]
    public long Id { get; set; }

    /// <summary>
    /// 工作類型 enum 值：1 AttachmentUpload、2 Report、3 M3u8Refresh
    /// </summary>
    public int WorkType { get; set; }

    /// <summary>
    /// 工作識別鍵，可用來查詢同一批工作
    /// </summary>
    [Required]
    [StringLength(200)]
    public string WorkKey { get; set; } = string.Empty;

    /// <summary>
    /// 工作參數 JSON
    /// </summary>
    [Required]
    public string PayloadJson { get; set; } = string.Empty;

    /// <summary>
    /// 優先順序，數字越小越早處理
    /// </summary>
    public int Priority { get; set; }

    /// <summary>
    /// 工作狀態：0 Pending、1 Processing、2 Succeeded、3 Failed、4 Canceled
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 已重試次數
    /// </summary>
    public int RetryCount { get; set; }

    /// <summary>
    /// 最大重試次數
    /// </summary>
    public int MaxRetryCount { get; set; }

    /// <summary>
    /// 預計執行時間
    /// </summary>
    public DateTime ScheduledTime { get; set; }

    /// <summary>
    /// 開始處理時間
    /// </summary>
    public DateTime? StartedTime { get; set; }

    /// <summary>
    /// 完成時間
    /// </summary>
    public DateTime? CompletedTime { get; set; }

    /// <summary>
    /// 工作鎖定到期時間
    /// </summary>
    public DateTime? LockedUntil { get; set; }

    /// <summary>
    /// 處理此工作的 worker 識別
    /// </summary>
    [Required]
    [StringLength(100)]
    public string LockedBy { get; set; } = string.Empty;

    /// <summary>
    /// 最後一次錯誤訊息
    /// </summary>
    [Required]
    public string LastError { get; set; } = string.Empty;

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CreatedId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime UpdatedTime { get; set; }

    /// <summary>
    /// 更新人員
    /// </summary>
    [Required]
    [StringLength(50)]
    public string UpdatedId { get; set; }

    /// <summary>
    /// 併發控制版本
    /// </summary>
    public Guid Version { get; set; }
}
