// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.LogDbContext;

public partial class LogDbContext : DbContext
{
    public LogDbContext(DbContextOptions<LogDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TokenRevocation> TokenRevocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TokenRevocation>(entity =>
        {
            entity.ToTable("TokenRevocation", tb => tb.HasComment("JWT Token 撤銷紀錄"));

            entity.Property(e => e.TokenId).HasComment("Token 唯一識別碼（JWT jti）");
            entity.Property(e => e.ExpiresUtc).HasComment("Token 到期時間（UTC）");
            entity.Property(e => e.RevokedTime).HasComment("撤銷時間（UTC）");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}