// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Template.DataAccess.LogDbContext;

/// <summary>
/// JWT Token 撤銷紀錄
/// </summary>
[Table("TokenRevocation")]
[Index("ExpiresUtc", Name = "IX_TokenRevocation_ExpiresUtc")]
public partial class TokenRevocation
{
    /// <summary>
    /// Token 唯一識別碼（JWT jti）
    /// </summary>
    [Key]
    [StringLength(128)]
    public string TokenId { get; set; }

    /// <summary>
    /// Token 到期時間（UTC）
    /// </summary>
    public DateTime ExpiresUtc { get; set; }

    /// <summary>
    /// 撤銷時間（UTC）
    /// </summary>
    public DateTime RevokedTime { get; set; }
}